[[redirects]]
  from = "/top/band"
  to = "https://peat-sun-countess.glitch.me/top/band"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
